### ISSUE TITLE
How are the GPU hours recorded

### ISSUE THREAD

**Issue by kwang2049** [terrierteam/pyterrier_doc2query#8]
Hi, really impressed by your interesting work. I have a question: how are the GPU hours in Table 2 recorded? I gave it try with your code myself: https://colab.research.google.com/drive/1Y-Q93GplU7dpnBSQZ3ed9drjRPFbk8wP?usp=sharing but it seems that it needs 1~2K hours on Colab's Tesla 4T GPU to process the MSMARCO collection (batch size = 32, `nsamples` = 40). This is very different from the reported one, i.e. 214. Thanks in advance.

P.S.: I also ran the same code on a V100 server and it still needs ~400 hours

**Comment by seanmacavaney** [comment]
Hi Kevin,

I have not tested the GPU hours on Colab or on a T4. We benchmarked on an nvidia 3090 GPU, which has a considerably faster clock speed and has more CUDA cores than T4.

However, I’d expect this all to be relative, so I wouldn’t expect the speedups to be different using different accelerators. The filtering will also be slower, likely at the same proportion.

Does this help?

**Comment by kwang2049** [comment]
OK, that could be the case. I did not expect that 3090 is faster than v100 before I read some blogs, but it should indeed be. Thanks for your reply. 

BTW, I found the code is using T5Tokenizer, which is much slower than T5TokenizerFast.

**Comment by cmacdonald** [comment]
Good spot on the tokeniser @kwang2049 . Could you try changing your notebook to see magnitude of difference? 

Our MonoT5/duoT5 crossencoder repo also uses the same tokenise

**Comment by kwang2049** [comment]
> 

The notebook already tried both of them. It reduces the GPU hours from ~2000 to ~1000.

**Comment by kwang2049** [comment]
> Good spot on the tokeniser @kwang2049 . Could you try changing your notebook to see magnitude of difference?
> 
> Our MonoT5/duoT5 crossencoder repo also uses the same tokenise

The notebook already tried both of them. See the line ```doc2query.tokenizer = T5TokenizerFast.from_pretrained("macavaney/doc2query-t5-base-msmarco")```. It reduces the GPU hours from ~2000 to ~1000.
